version: '3'

services:
  mariadb:
    image: mariadb:10.8.6
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: playerdb
      MARIADB_USER: playerdbuser
      MARIADB_PASSWORD: 123456

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mariadb

